[build]
    functions = "functions"

[[redirects]]
    to="/.netlify/functions/api/*"
    from="/api/*"
    status=200

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"